
version: '3' 

services:
  proxy:
    image: jwilder/nginx-proxy
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - local
  backend:
    build: ./backend/
    environment:
      REDIS_HOST: cache
      POSTGRES_HOST: db
      POSTGRES_USER: possu
      POSTGRES_PASSWORD: possu123
      POSTGRES_DATABASE: possu

    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - local

  frontend:
    build: ./frontend/
    ports:
      - 5000:5000
    networks:
      - local
    environment:
      # Only changed this
      - API_URL=/api/

  cache:
    image: redis
    ports:
      - 6379:6379
    networks:
      - local

  db:
    image: postgres
    environment:
      # These should be read from somewhere else with e.g. POSTGRES_USER: ${POSTGRES_USER} syntax
      POSTGRES_USER: possu
      POSTGRES_PASSWORD: possu123
      POSTGRES_DB: possu
    networks:
      - local

networks:
  local:
