version: '3' 

services:
  backend:
    build: ./backend/
    environment:
      REDIS_HOST: cache
    ports:
      - 8080:8080
    restart: unless-stopped

  frontend:
    build: ./frontend/
    ports:
      - 5000:5000

  cache:
    image: redis
    ports:
      - 6379:6379

